"""criar tabelas iniciais

Revision ID: a7b7021b3418
Revises: 
Create Date: 2026-08-04 11:46:27.905886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7b7021b3418'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motoboys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('disponivel', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saidas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('motoboy_id', sa.String(), nullable=False),
    sa.Column('status_saida', sa.Enum('SUGERIDA', 'CONFIRMADA', 'EM_ANDAMENTO', 'FINALIZADA', name='status_saidae'), nullable=True),
    sa.Column('horario_criacao', sa.DateTime(), nullable=True),
    sa.Column('horario_confirmacao', sa.DateTime(), nullable=True),
    sa.Column('horario_finalizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['motoboy_id'], ['motoboys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cliente', sa.String(), nullable=False),
    sa.Column('endereco', sa.String(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('complemento', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=False),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('cep', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('horario_limite', sa.DateTime(), nullable=True),
    sa.Column('forma_pagamento', sa.String(), nullable=False),
    sa.Column('observacao', sa.String(), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('FILA', 'EM_SAIDA', 'ENTREGUE', 'LOCALIZACAO_PENDENTE', 'CANCELADO', name='status_pedidoe'), nullable=True),
    sa.Column('saida_id', sa.String(), nullable=True),
    sa.Column('ordem_na_saida', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['saida_id'], ['saidas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedidos')
    op.drop_table('saidas')
    op.drop_table('motoboys')
    # ### end Alembic commands ###
